---
extends:
    - airbnb-base
    - plugin:vue/recommended
    - plugin:nuxt/recommended

env:
    node: true
    browser: true
    es6: true

parserOptions:
    parser: babel-eslint
    sourceType: module

rules:
    indent:
        - warn
        - 4
        -
            SwitchCase: 1
    max-len:
        - warn
        -
            code: 80
    no-console:
        - warn
        -
            allow:
                - warn
                - error
    spaced-comment: warn
    linebreak-style: off
    no-multiple-empty-lines:
        - error
        -
            max: 1
            maxEOF: 1
    semi:
        - error
        - never
        -
            beforeStatementContinuationChars: always
    comma-dangle:
        - warn
        -
            arrays: only-multiline
            objects: only-multiline
            imports: never
            exports: never
            functions: only-multiline
    class-methods-use-this: off
    no-nested-ternary: error
    no-unneeded-ternary: error
    func-names:
        - error
        - as-needed
    arrow-parens: off
    arrow-body-style: off
    no-restricted-syntax: off
    require-await: off
    operator-linebreak:
            - warn
            - before
#
# Vue specific
#
    vue/script-indent:
        - warn
        - 4
        -
            baseIndent: 1
            switchCase: 1
    vue/html-indent:
        - warn
        - 4
    vue/html-closing-bracket-spacing:
        - warn
        -
            selfClosingTag: never
    no-shadow:
        - error
        -
            allow:
                - state
                - getters
    no-param-reassign: off # Disabled because of how Vue handle state mutation
    vue/max-attributes-per-line:
        - warn
        -
            singleline: 2
    vue/attributes-order: off
    import/no-unresolved: off
    import/extensions: off
overrides:
    -
        files:
            - '*.vue'
        rules:
            indent: off



